# Generated by deps/generate.jl from plotly.js v4.1.1's plot-schema.json.  Don't edit by hand.

# Trace type => its attributes (top-level only)
const schema = Dict{Symbol, Set{Symbol}}(
    :bar => Set([
        :alignmentgroup, :base, :cliponaxis, :constraintext, :customdata, :dx, :dy, :error_x, :error_y, :hoverinfo,
        :hoverlabel, :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :insidetextanchor, :insidetextfont,
        :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :marker, :meta, :name, :offset,
        :offsetgroup, :opacity, :orientation, :outsidetextfont, :selected, :selectedpoints, :showlegend, :text,
        :textangle, :textfont, :textposition, :texttemplate, :texttemplatefallback, :type, :uid, :uirevision,
        :unselected, :visible, :width, :x, :x0, :xaxis, :xcalendar, :xhoverformat, :xperiod, :xperiod0,
        :xperiodalignment, :y, :y0, :yaxis, :ycalendar, :yhoverformat, :yperiod, :yperiod0, :yperiodalignment, :zorder
    ]),
    :barpolar => Set([
        :base, :customdata, :dr, :dtheta, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback, :hovertext,
        :ids, :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :marker, :meta, :name, :offset,
        :opacity, :r, :r0, :selected, :selectedpoints, :showlegend, :subplot, :text, :theta, :theta0, :thetaunit, :type,
        :uid, :uirevision, :unselected, :visible, :width
    ]),
    :box => Set([
        :alignmentgroup, :boxmean, :boxpoints, :customdata, :dx, :dy, :fillcolor, :hoverinfo, :hoverlabel, :hoveron,
        :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :jitter, :legend, :legendgroup, :legendgrouptitle,
        :legendrank, :legendwidth, :line, :lowerfence, :marker, :mean, :median, :meta, :name, :notched, :notchspan,
        :notchwidth, :offsetgroup, :opacity, :orientation, :pointpos, :q1, :q3, :quartilemethod, :sd, :sdmultiple,
        :selected, :selectedpoints, :showlegend, :showwhiskers, :sizemode, :text, :type, :uid, :uirevision, :unselected,
        :upperfence, :visible, :whiskerwidth, :width, :x, :x0, :xaxis, :xcalendar, :xhoverformat, :xperiod, :xperiod0,
        :xperiodalignment, :y, :y0, :yaxis, :ycalendar, :yhoverformat, :yperiod, :yperiod0, :yperiodalignment, :zorder
    ]),
    :candlestick => Set([
        :close, :customdata, :decreasing, :high, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback,
        :hovertext, :ids, :increasing, :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :line, :low,
        :meta, :name, :opacity, :open, :selectedpoints, :showlegend, :text, :type, :uid, :uirevision, :visible,
        :whiskerwidth, :x, :xaxis, :xcalendar, :xhoverformat, :xperiod, :xperiod0, :xperiodalignment, :yaxis,
        :yhoverformat, :zorder
    ]),
    :carpet => Set([
        :a, :a0, :aaxis, :b, :b0, :baxis, :carpet, :cheaterslope, :color, :customdata, :da, :db, :font, :ids, :legend,
        :legendgrouptitle, :legendrank, :legendwidth, :meta, :name, :opacity, :type, :uid, :uirevision, :visible, :x,
        :xaxis, :y, :yaxis, :zorder
    ]),
    :choropleth => Set([
        :autocolorscale, :coloraxis, :colorbar, :colorscale, :customdata, :featureidkey, :geo, :geojson, :hoverinfo,
        :hoverlabel, :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle,
        :legendrank, :legendwidth, :locationmode, :locations, :marker, :meta, :name, :reversescale, :selected,
        :selectedpoints, :showlegend, :showscale, :text, :type, :uid, :uirevision, :unselected, :visible, :z, :zauto,
        :zmax, :zmid, :zmin
    ]),
    :choroplethmap => Set([
        :autocolorscale, :below, :coloraxis, :colorbar, :colorscale, :customdata, :featureidkey, :geojson, :hoverinfo,
        :hoverlabel, :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle,
        :legendrank, :legendwidth, :locations, :marker, :meta, :name, :reversescale, :selected, :selectedpoints,
        :showlegend, :showscale, :subplot, :text, :type, :uid, :uirevision, :unselected, :visible, :z, :zauto, :zmax,
        :zmid, :zmin
    ]),
    :cone => Set([
        :anchor, :autocolorscale, :cauto, :cmax, :cmid, :cmin, :coloraxis, :colorbar, :colorscale, :customdata,
        :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup,
        :legendgrouptitle, :legendrank, :legendwidth, :lighting, :lightposition, :meta, :name, :opacity, :reversescale,
        :scene, :showlegend, :showscale, :sizemode, :sizeref, :text, :type, :u, :uhoverformat, :uid, :uirevision, :v,
        :vhoverformat, :visible, :w, :whoverformat, :x, :xhoverformat, :y, :yhoverformat, :z, :zhoverformat
    ]),
    :contour => Set([
        :autocolorscale, :autocontour, :coloraxis, :colorbar, :colorscale, :connectgaps, :contours, :customdata, :dx,
        :dy, :fillcolor, :hoverinfo, :hoverlabel, :hoverongaps, :hovertemplate, :hovertemplatefallback, :hovertext,
        :ids, :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :line, :meta, :name, :ncontours,
        :opacity, :reversescale, :showlegend, :showscale, :text, :textfont, :texttemplate, :texttemplatefallback,
        :transpose, :type, :uid, :uirevision, :visible, :x, :x0, :xaxis, :xcalendar, :xhoverformat, :xperiod, :xperiod0,
        :xperiodalignment, :xtype, :y, :y0, :yaxis, :ycalendar, :yhoverformat, :yperiod, :yperiod0, :yperiodalignment,
        :ytype, :z, :zauto, :zhoverformat, :zmax, :zmid, :zmin, :zorder
    ]),
    :contourcarpet => Set([
        :a, :a0, :atype, :autocolorscale, :autocontour, :b, :b0, :btype, :carpet, :coloraxis, :colorbar, :colorscale,
        :contours, :customdata, :da, :db, :fillcolor, :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle,
        :legendrank, :legendwidth, :line, :meta, :name, :ncontours, :opacity, :reversescale, :showlegend, :showscale,
        :text, :transpose, :type, :uid, :uirevision, :visible, :xaxis, :yaxis, :z, :zauto, :zmax, :zmid, :zmin, :zorder
    ]),
    :densitymap => Set([
        :autocolorscale, :below, :coloraxis, :colorbar, :colorscale, :customdata, :hoverinfo, :hoverlabel,
        :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :lat, :legend, :legendgroup, :legendgrouptitle,
        :legendrank, :legendwidth, :lon, :meta, :name, :opacity, :radius, :reversescale, :showlegend, :showscale,
        :subplot, :text, :type, :uid, :uirevision, :visible, :z, :zauto, :zmax, :zmid, :zmin
    ]),
    :funnel => Set([
        :alignmentgroup, :cliponaxis, :connector, :constraintext, :customdata, :dx, :dy, :hoverinfo, :hoverlabel,
        :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :insidetextanchor, :insidetextfont, :legend,
        :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :marker, :meta, :name, :offset, :offsetgroup,
        :opacity, :orientation, :outsidetextfont, :selectedpoints, :showlegend, :text, :textangle, :textfont, :textinfo,
        :textposition, :texttemplate, :texttemplatefallback, :type, :uid, :uirevision, :visible, :width, :x, :x0,
        :xaxis, :xhoverformat, :xperiod, :xperiod0, :xperiodalignment, :y, :y0, :yaxis, :yhoverformat, :yperiod,
        :yperiod0, :yperiodalignment, :zorder
    ]),
    :funnelarea => Set([
        :aspectratio, :baseratio, :customdata, :dlabel, :domain, :hoverinfo, :hoverlabel, :hovertemplate,
        :hovertemplatefallback, :hovertext, :ids, :insidetextfont, :label0, :labels, :legend, :legendgroup,
        :legendgrouptitle, :legendrank, :legendwidth, :marker, :meta, :name, :opacity, :scalegroup, :showlegend, :text,
        :textfont, :textinfo, :textposition, :texttemplate, :texttemplatefallback, :title, :type, :uid, :uirevision,
        :values, :visible
    ]),
    :heatmap => Set([
        :autocolorscale, :coloraxis, :colorbar, :colorscale, :connectgaps, :customdata, :dx, :dy, :hoverinfo,
        :hoverlabel, :hoverongaps, :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup,
        :legendgrouptitle, :legendrank, :legendwidth, :meta, :name, :opacity, :reversescale, :showlegend, :showscale,
        :text, :textfont, :texttemplate, :texttemplatefallback, :transpose, :type, :uid, :uirevision, :visible, :x, :x0,
        :xaxis, :xcalendar, :xgap, :xhoverformat, :xperiod, :xperiod0, :xperiodalignment, :xtype, :y, :y0, :yaxis,
        :ycalendar, :ygap, :yhoverformat, :yperiod, :yperiod0, :yperiodalignment, :ytype, :z, :zauto, :zhoverformat,
        :zmax, :zmid, :zmin, :zorder, :zsmooth
    ]),
    :histogram => Set([
        :alignmentgroup, :autobinx, :autobiny, :bingroup, :cliponaxis, :constraintext, :cumulative, :customdata,
        :error_x, :error_y, :histfunc, :histnorm, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback,
        :hovertext, :ids, :insidetextanchor, :insidetextfont, :legend, :legendgroup, :legendgrouptitle, :legendrank,
        :legendwidth, :marker, :meta, :name, :nbinsx, :nbinsy, :offsetgroup, :opacity, :orientation, :outsidetextfont,
        :selected, :selectedpoints, :showlegend, :text, :textangle, :textfont, :textposition, :texttemplate,
        :texttemplatefallback, :type, :uid, :uirevision, :unselected, :visible, :x, :xaxis, :xbins, :xcalendar,
        :xhoverformat, :y, :yaxis, :ybins, :ycalendar, :yhoverformat, :zorder
    ]),
    :histogram2d => Set([
        :autobinx, :autobiny, :autocolorscale, :bingroup, :coloraxis, :colorbar, :colorscale, :customdata, :histfunc,
        :histnorm, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback, :ids, :legend, :legendgroup,
        :legendgrouptitle, :legendrank, :legendwidth, :marker, :meta, :name, :nbinsx, :nbinsy, :opacity, :reversescale,
        :showlegend, :showscale, :textfont, :texttemplate, :texttemplatefallback, :type, :uid, :uirevision, :visible,
        :x, :xaxis, :xbingroup, :xbins, :xcalendar, :xgap, :xhoverformat, :y, :yaxis, :ybingroup, :ybins, :ycalendar,
        :ygap, :yhoverformat, :z, :zauto, :zhoverformat, :zmax, :zmid, :zmin, :zsmooth
    ]),
    :histogram2dcontour => Set([
        :autobinx, :autobiny, :autocolorscale, :autocontour, :bingroup, :coloraxis, :colorbar, :colorscale, :contours,
        :customdata, :histfunc, :histnorm, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback, :ids,
        :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :line, :marker, :meta, :name, :nbinsx,
        :nbinsy, :ncontours, :opacity, :reversescale, :showlegend, :showscale, :textfont, :texttemplate,
        :texttemplatefallback, :type, :uid, :uirevision, :visible, :x, :xaxis, :xbingroup, :xbins, :xcalendar,
        :xhoverformat, :y, :yaxis, :ybingroup, :ybins, :ycalendar, :yhoverformat, :z, :zauto, :zhoverformat, :zmax,
        :zmid, :zmin
    ]),
    :icicle => Set([
        :branchvalues, :count, :customdata, :domain, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback,
        :hovertext, :ids, :insidetextfont, :labels, :leaf, :legend, :legendgrouptitle, :legendrank, :legendwidth,
        :level, :marker, :maxdepth, :meta, :name, :opacity, :outsidetextfont, :parents, :pathbar, :root, :sort, :text,
        :textfont, :textinfo, :textposition, :texttemplate, :texttemplatefallback, :tiling, :type, :uid, :uirevision,
        :values, :visible
    ]),
    :image => Set([
        :colormodel, :customdata, :dx, :dy, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback, :hovertext,
        :ids, :legend, :legendgrouptitle, :legendrank, :legendwidth, :meta, :name, :opacity, :source, :text, :type,
        :uid, :uirevision, :visible, :x0, :xaxis, :y0, :yaxis, :z, :zmax, :zmin, :zorder, :zsmooth
    ]),
    :indicator => Set([
        :align, :customdata, :delta, :domain, :gauge, :ids, :legend, :legendgrouptitle, :legendrank, :legendwidth,
        :meta, :mode, :name, :number, :title, :type, :uid, :uirevision, :value, :visible
    ]),
    :isosurface => Set([
        :autocolorscale, :caps, :cauto, :cmax, :cmid, :cmin, :coloraxis, :colorbar, :colorscale, :contour, :customdata,
        :flatshading, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :isomax,
        :isomin, :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :lighting, :lightposition, :meta,
        :name, :opacity, :reversescale, :scene, :showlegend, :showscale, :slices, :spaceframe, :surface, :text, :type,
        :uid, :uirevision, :value, :valuehoverformat, :visible, :x, :xhoverformat, :y, :yhoverformat, :z, :zhoverformat
    ]),
    :mesh3d => Set([
        :alphahull, :autocolorscale, :cauto, :cmax, :cmid, :cmin, :color, :coloraxis, :colorbar, :colorscale, :contour,
        :customdata, :delaunayaxis, :facecolor, :flatshading, :hoverinfo, :hoverlabel, :hovertemplate,
        :hovertemplatefallback, :hovertext, :i, :ids, :intensity, :intensitymode, :j, :k, :legend, :legendgroup,
        :legendgrouptitle, :legendrank, :legendwidth, :lighting, :lightposition, :meta, :name, :opacity, :reversescale,
        :scene, :showlegend, :showscale, :text, :type, :uid, :uirevision, :vertexcolor, :visible, :x, :xcalendar,
        :xhoverformat, :y, :ycalendar, :yhoverformat, :z, :zcalendar, :zhoverformat
    ]),
    :ohlc => Set([
        :close, :customdata, :decreasing, :high, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback,
        :hovertext, :ids, :increasing, :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :line, :low,
        :meta, :name, :opacity, :open, :selectedpoints, :showlegend, :text, :tickwidth, :type, :uid, :uirevision,
        :visible, :x, :xaxis, :xcalendar, :xhoverformat, :xperiod, :xperiod0, :xperiodalignment, :yaxis, :yhoverformat,
        :zorder
    ]),
    :parcats => Set([
        :arrangement, :bundlecolors, :counts, :dimensions, :domain, :hoverinfo, :hoveron, :hovertemplate,
        :hovertemplatefallback, :labelfont, :legendgrouptitle, :legendwidth, :line, :meta, :name, :sortpaths, :tickfont,
        :type, :uid, :uirevision, :visible
    ]),
    :parcoords => Set([
        :customdata, :dimensions, :domain, :ids, :labelangle, :labelfont, :labelside, :legend, :legendgrouptitle,
        :legendrank, :legendwidth, :line, :meta, :name, :rangefont, :tickfont, :type, :uid, :uirevision, :unselected,
        :visible
    ]),
    :pie => Set([
        :automargin, :customdata, :direction, :dlabel, :domain, :hole, :hoverinfo, :hoverlabel, :hovertemplate,
        :hovertemplatefallback, :hovertext, :ids, :insidetextfont, :insidetextorientation, :label0, :labels, :legend,
        :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :marker, :meta, :name, :opacity, :outsidetextfont,
        :pull, :rotation, :scalegroup, :showlegend, :sort, :text, :textfont, :textinfo, :textposition, :texttemplate,
        :texttemplatefallback, :title, :type, :uid, :uirevision, :values, :visible
    ]),
    :quiver => Set([
        :anchor, :arrowref, :customdata, :dx, :dy, :hoverinfo, :hoverlabel, :hovertemplate, :ids, :legend, :legendgroup,
        :legendgrouptitle, :legendrank, :legendwidth, :lengthfactor, :lengthmode, :marker, :meta, :name, :opacity,
        :selected, :selectedpoints, :showlegend, :text, :textfont, :textposition, :type, :u, :uhoverformat, :uid,
        :uirevision, :unselected, :v, :vhoverformat, :visible, :x, :x0, :xaxis, :xhoverformat, :y, :y0, :yaxis,
        :yhoverformat
    ]),
    :sankey => Set([
        :arrangement, :customdata, :direction, :domain, :hoverinfo, :hoverlabel, :ids, :legend, :legendgrouptitle,
        :legendrank, :legendwidth, :link, :meta, :name, :node, :orientation, :selectedpoints, :textfont, :type, :uid,
        :uirevision, :valueformat, :valuesuffix, :visible
    ]),
    :scatter => Set([
        :alignmentgroup, :cliponaxis, :connectgaps, :customdata, :dx, :dy, :error_x, :error_y, :fill, :fillcolor,
        :fillgradient, :fillpattern, :groupnorm, :hoverinfo, :hoverlabel, :hoveron, :hovertemplate,
        :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth,
        :line, :marker, :meta, :mode, :name, :offsetgroup, :opacity, :orientation, :selected, :selectedpoints,
        :showlegend, :stackgaps, :stackgroup, :text, :textfont, :textposition, :texttemplate, :texttemplatefallback,
        :type, :uid, :uirevision, :unselected, :visible, :x, :x0, :xaxis, :xcalendar, :xhoverformat, :xperiod,
        :xperiod0, :xperiodalignment, :y, :y0, :yaxis, :ycalendar, :yhoverformat, :yperiod, :yperiod0,
        :yperiodalignment, :zorder
    ]),
    :scatter3d => Set([
        :connectgaps, :customdata, :error_x, :error_y, :error_z, :hoverinfo, :hoverlabel, :hovertemplate,
        :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth,
        :line, :marker, :meta, :mode, :name, :opacity, :projection, :scene, :showlegend, :surfaceaxis, :surfacecolor,
        :text, :textfont, :textposition, :texttemplate, :texttemplatefallback, :type, :uid, :uirevision, :visible, :x,
        :xcalendar, :xhoverformat, :y, :ycalendar, :yhoverformat, :z, :zcalendar, :zhoverformat
    ]),
    :scattercarpet => Set([
        :a, :b, :carpet, :connectgaps, :customdata, :fill, :fillcolor, :hoverinfo, :hoverlabel, :hoveron,
        :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle, :legendrank,
        :legendwidth, :line, :marker, :meta, :mode, :name, :opacity, :selected, :selectedpoints, :showlegend, :text,
        :textfont, :textposition, :texttemplate, :texttemplatefallback, :type, :uid, :uirevision, :unselected, :visible,
        :xaxis, :yaxis, :zorder
    ]),
    :scattergeo => Set([
        :connectgaps, :customdata, :featureidkey, :fill, :fillcolor, :geo, :geojson, :hoverinfo, :hoverlabel,
        :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :lat, :legend, :legendgroup, :legendgrouptitle,
        :legendrank, :legendwidth, :line, :locationmode, :locations, :lon, :marker, :meta, :mode, :name, :opacity,
        :selected, :selectedpoints, :showlegend, :text, :textfont, :textposition, :texttemplate, :texttemplatefallback,
        :type, :uid, :uirevision, :unselected, :visible
    ]),
    :scattergl => Set([
        :connectgaps, :customdata, :dx, :dy, :error_x, :error_y, :fill, :fillcolor, :hoverinfo, :hoverlabel,
        :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle, :legendrank,
        :legendwidth, :line, :marker, :meta, :mode, :name, :opacity, :selected, :selectedpoints, :showlegend, :text,
        :textfont, :textposition, :texttemplate, :texttemplatefallback, :type, :uid, :uirevision, :unselected, :visible,
        :x, :x0, :xaxis, :xcalendar, :xhoverformat, :xperiod, :xperiod0, :xperiodalignment, :y, :y0, :yaxis, :ycalendar,
        :yhoverformat, :yperiod, :yperiod0, :yperiodalignment
    ]),
    :scattermap => Set([
        :below, :cluster, :connectgaps, :customdata, :fill, :fillcolor, :hoverinfo, :hoverlabel, :hovertemplate,
        :hovertemplatefallback, :hovertext, :ids, :lat, :legend, :legendgroup, :legendgrouptitle, :legendrank,
        :legendwidth, :line, :lon, :marker, :meta, :mode, :name, :opacity, :selected, :selectedpoints, :showlegend,
        :subplot, :text, :textfont, :textposition, :texttemplate, :texttemplatefallback, :type, :uid, :uirevision,
        :unselected, :visible
    ]),
    :scatterpolar => Set([
        :cliponaxis, :connectgaps, :customdata, :dr, :dtheta, :fill, :fillcolor, :hoverinfo, :hoverlabel, :hoveron,
        :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle, :legendrank,
        :legendwidth, :line, :marker, :meta, :mode, :name, :opacity, :r, :r0, :selected, :selectedpoints, :showlegend,
        :subplot, :text, :textfont, :textposition, :texttemplate, :texttemplatefallback, :theta, :theta0, :thetaunit,
        :type, :uid, :uirevision, :unselected, :visible
    ]),
    :scatterpolargl => Set([
        :connectgaps, :customdata, :dr, :dtheta, :fill, :fillcolor, :hoverinfo, :hoverlabel, :hovertemplate,
        :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth,
        :line, :marker, :meta, :mode, :name, :opacity, :r, :r0, :selected, :selectedpoints, :showlegend, :subplot,
        :text, :textfont, :textposition, :texttemplate, :texttemplatefallback, :theta, :theta0, :thetaunit, :type, :uid,
        :uirevision, :unselected, :visible
    ]),
    :scattersmith => Set([
        :cliponaxis, :connectgaps, :customdata, :fill, :fillcolor, :hoverinfo, :hoverlabel, :hoveron, :hovertemplate,
        :hovertemplatefallback, :hovertext, :ids, :imag, :legend, :legendgroup, :legendgrouptitle, :legendrank,
        :legendwidth, :line, :marker, :meta, :mode, :name, :opacity, :real, :selected, :selectedpoints, :showlegend,
        :subplot, :text, :textfont, :textposition, :texttemplate, :texttemplatefallback, :type, :uid, :uirevision,
        :unselected, :visible
    ]),
    :scatterternary => Set([
        :a, :b, :c, :cliponaxis, :connectgaps, :customdata, :fill, :fillcolor, :hoverinfo, :hoverlabel, :hoveron,
        :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle, :legendrank,
        :legendwidth, :line, :marker, :meta, :mode, :name, :opacity, :selected, :selectedpoints, :showlegend, :subplot,
        :sum, :text, :textfont, :textposition, :texttemplate, :texttemplatefallback, :type, :uid, :uirevision,
        :unselected, :visible
    ]),
    :splom => Set([
        :customdata, :diagonal, :dimensions, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback,
        :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :marker, :meta, :name,
        :opacity, :selected, :selectedpoints, :showlegend, :showlowerhalf, :showupperhalf, :text, :type, :uid,
        :uirevision, :unselected, :visible, :xaxes, :xhoverformat, :yaxes, :yhoverformat
    ]),
    :streamtube => Set([
        :autocolorscale, :cauto, :cmax, :cmid, :cmin, :coloraxis, :colorbar, :colorscale, :customdata, :hoverinfo,
        :hoverlabel, :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :legend, :legendgroup, :legendgrouptitle,
        :legendrank, :legendwidth, :lighting, :lightposition, :maxdisplayed, :meta, :name, :opacity, :reversescale,
        :scene, :showlegend, :showscale, :sizeref, :starts, :text, :type, :u, :uhoverformat, :uid, :uirevision, :v,
        :vhoverformat, :visible, :w, :whoverformat, :x, :xhoverformat, :y, :yhoverformat, :z, :zhoverformat
    ]),
    :sunburst => Set([
        :branchvalues, :count, :customdata, :domain, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback,
        :hovertext, :ids, :insidetextfont, :insidetextorientation, :labels, :leaf, :legend, :legendgrouptitle,
        :legendrank, :legendwidth, :level, :marker, :maxdepth, :meta, :name, :opacity, :outsidetextfont, :parents,
        :root, :rotation, :sort, :text, :textfont, :textinfo, :texttemplate, :texttemplatefallback, :type, :uid,
        :uirevision, :values, :visible
    ]),
    :surface => Set([
        :autocolorscale, :cauto, :cmax, :cmid, :cmin, :coloraxis, :colorbar, :colorscale, :connectgaps, :contours,
        :customdata, :hidesurface, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback, :hovertext, :ids,
        :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :lighting, :lightposition, :meta, :name,
        :opacity, :opacityscale, :reversescale, :scene, :showlegend, :showscale, :surfacecolor, :text, :type, :uid,
        :uirevision, :visible, :x, :xcalendar, :xhoverformat, :y, :ycalendar, :yhoverformat, :z, :zcalendar,
        :zhoverformat
    ]),
    :table => Set([
        :cells, :columnorder, :columnwidth, :customdata, :domain, :editType, :header, :hoverinfo, :hoverlabel, :ids,
        :legend, :legendgrouptitle, :legendrank, :legendwidth, :meta, :name, :type, :uid, :uirevision, :visible
    ]),
    :treemap => Set([
        :branchvalues, :count, :customdata, :domain, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback,
        :hovertext, :ids, :insidetextfont, :labels, :legend, :legendgrouptitle, :legendrank, :legendwidth, :level,
        :marker, :maxdepth, :meta, :name, :opacity, :outsidetextfont, :parents, :pathbar, :root, :sort, :text,
        :textfont, :textinfo, :textposition, :texttemplate, :texttemplatefallback, :tiling, :type, :uid, :uirevision,
        :values, :visible
    ]),
    :violin => Set([
        :alignmentgroup, :bandwidth, :box, :customdata, :fillcolor, :hoverinfo, :hoverlabel, :hoveron, :hovertemplate,
        :hovertemplatefallback, :hovertext, :ids, :jitter, :legend, :legendgroup, :legendgrouptitle, :legendrank,
        :legendwidth, :line, :marker, :meanline, :meta, :name, :offsetgroup, :opacity, :orientation, :pointpos, :points,
        :quartilemethod, :scalegroup, :scalemode, :selected, :selectedpoints, :showlegend, :side, :span, :spanmode,
        :text, :type, :uid, :uirevision, :unselected, :visible, :width, :x, :x0, :xaxis, :xhoverformat, :y, :y0, :yaxis,
        :yhoverformat, :zorder
    ]),
    :volume => Set([
        :autocolorscale, :caps, :cauto, :cmax, :cmid, :cmin, :coloraxis, :colorbar, :colorscale, :contour, :customdata,
        :flatshading, :hoverinfo, :hoverlabel, :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :isomax,
        :isomin, :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :lighting, :lightposition, :meta,
        :name, :opacity, :opacityscale, :reversescale, :scene, :showlegend, :showscale, :slices, :spaceframe, :surface,
        :text, :type, :uid, :uirevision, :value, :valuehoverformat, :visible, :x, :xhoverformat, :y, :yhoverformat, :z,
        :zhoverformat
    ]),
    :waterfall => Set([
        :alignmentgroup, :base, :cliponaxis, :connector, :constraintext, :customdata, :decreasing, :dx, :dy, :hoverinfo,
        :hoverlabel, :hovertemplate, :hovertemplatefallback, :hovertext, :ids, :increasing, :insidetextanchor,
        :insidetextfont, :legend, :legendgroup, :legendgrouptitle, :legendrank, :legendwidth, :measure, :meta, :name,
        :offset, :offsetgroup, :opacity, :orientation, :outsidetextfont, :selectedpoints, :showlegend, :text,
        :textangle, :textfont, :textinfo, :textposition, :texttemplate, :texttemplatefallback, :totals, :type, :uid,
        :uirevision, :visible, :width, :x, :x0, :xaxis, :xhoverformat, :xperiod, :xperiod0, :xperiodalignment, :y, :y0,
        :yaxis, :yhoverformat, :yperiod, :yperiod0, :yperiodalignment, :zorder
    ]),
)
